<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Snapshot the current catalog into runnable seeder files.
 *
 * Produces two files under database/seeders/:
 *   - ExportedProductCategoriesSeeder.php  (table: product_categories)
 *   - ExportedProductsSeeder.php           (tables: products + product_product_category)
 *
 * The seeders truncate each table before inserting, run with foreign-key
 * checks disabled (so re-runs and parent/child rows don't fight each other),
 * and preserve original row IDs so cross-table references stay valid.
 *
 *   php artisan catalog:export
 *   php artisan db:seed --class=ExportedProductCategoriesSeeder
 *   php artisan db:seed --class=ExportedProductsSeeder
 */
class ExportCatalog extends Command
{
    protected $signature = 'catalog:export {--chunk=100 : Rows per insert() call in the generated seeders}';

    protected $description = 'Export product_categories, products, and the pivot table into runnable seeder files.';

    public function handle(): int
    {
        $chunk = max(1, (int) $this->option('chunk'));

        $catCount = $this->writeCategoriesSeeder($chunk);
        [$productCount, $pivotCount] = $this->writeProductsSeeder($chunk);

        $this->newLine();
        $this->info('Wrote:');
        $this->line("  database/seeders/ExportedProductCategoriesSeeder.php  ({$catCount} rows)");
        $this->line("  database/seeders/ExportedProductsSeeder.php           ({$productCount} products, {$pivotCount} pivot rows)");
        $this->newLine();
        $this->line('To import on another instance:');
        $this->line('  php artisan db:seed --class=ExportedProductCategoriesSeeder');
        $this->line('  php artisan db:seed --class=ExportedProductsSeeder');

        return self::SUCCESS;
    }

    private function writeCategoriesSeeder(int $chunk): int
    {
        $rows = $this->fetch('product_categories');

        $body = $this->buildTableBlock('product_categories', $rows, $chunk);

        file_put_contents(
            database_path('seeders/ExportedProductCategoriesSeeder.php'),
            $this->wrapSeeder('ExportedProductCategoriesSeeder', $body),
        );

        return count($rows);
    }

    private function writeProductsSeeder(int $chunk): array
    {
        $products = $this->fetch('products');
        $pivot = $this->fetch('product_product_category');

        $body = $this->buildTableBlock('products', $products, $chunk)
            .$this->buildTableBlock('product_product_category', $pivot, $chunk);

        file_put_contents(
            database_path('seeders/ExportedProductsSeeder.php'),
            $this->wrapSeeder('ExportedProductsSeeder', $body),
        );

        return [count($products), count($pivot)];
    }

    /** @return array<int,array<string,mixed>> */
    private function fetch(string $table): array
    {
        return DB::table($table)
            ->orderBy('id')
            ->get()
            ->map(fn ($r) => (array) $r)
            ->all();
    }

    private function buildTableBlock(string $table, array $rows, int $chunk): string
    {
        $out = "        DB::table('{$table}')->truncate();\n";

        if (empty($rows)) {
            return $out."\n";
        }

        foreach (array_chunk($rows, $chunk) as $batch) {
            $exported = $this->exportRows($batch);
            $out .= "        DB::table('{$table}')->insert({$exported});\n";
        }

        return $out."\n";
    }

    /**
     * Render an array of associative rows as a compact PHP literal.
     * One row per line keeps diffs readable; var_export's default
     * `array (\n  'k' => 'v',\n)` shape is too verbose for many rows.
     */
    private function exportRows(array $rows): string
    {
        $lines = [];
        foreach ($rows as $row) {
            $parts = [];
            foreach ($row as $col => $val) {
                $parts[] = var_export($col, true).' => '.var_export($val, true);
            }
            $lines[] = '            ['.implode(', ', $parts).'],';
        }

        return "[\n".implode("\n", $lines)."\n        ]";
    }

    private function wrapSeeder(string $class, string $body): string
    {
        // Trim the trailing blank line so the file ends cleanly.
        $body = rtrim($body)."\n";

        return <<<PHP
        <?php

        namespace Database\\Seeders;

        use Illuminate\\Database\\Seeder;
        use Illuminate\\Support\\Facades\\DB;
        use Illuminate\\Support\\Facades\\Schema;

        /**
         * Generated by `php artisan catalog:export`. Do not edit by hand —
         * re-run the command to refresh the snapshot.
         */
        class {$class} extends Seeder
        {
            public function run(): void
            {
                Schema::disableForeignKeyConstraints();

        {$body}
                Schema::enableForeignKeyConstraints();
            }
        }
        PHP;
    }
}
