<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Generated by `php artisan catalog:export`. Do not edit by hand —
 * re-run the command to refresh the snapshot.
 */
class ExportedProductCategoriesSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        DB::table('product_categories')->truncate();
        DB::table('product_categories')->insert([
            ['id' => 1, 'parent_id' => NULL, 'name' => 'Chairs', 'slug' => 'chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 2, 'parent_id' => 24, 'name' => 'Plastic Folding Chairs', 'slug' => 'plastic-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/plastic-folding-chair-ii-black/b0f94b997e24.png'],
            ['id' => 3, 'parent_id' => 24, 'name' => 'Wood Folding Chairs', 'slug' => 'wood-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 4, 'parent_id' => 24, 'name' => 'Metal Folding Chairs', 'slug' => 'metal-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/premium-double-braced-steel-folding-chair-grey/bac02fbecff3.jpg'],
            ['id' => 5, 'parent_id' => 24, 'name' => 'Bamboo Folding Chairs', 'slug' => 'bamboo-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 6, 'parent_id' => 24, 'name' => 'Resin Folding Chairs', 'slug' => 'resin-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 7, 'parent_id' => 24, 'name' => 'Folding Chairs Cushions & Covers', 'slug' => 'folding-chairs-cushions-and-covers', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 8, 'parent_id' => 24, 'name' => 'Folding Chairs Parts & Dollies', 'slug' => 'folding-chairs-parts-and-dollies', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 9, 'parent_id' => 24, 'name' => 'Clear Folding Chairs', 'slug' => 'clear-folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 10, 'parent_id' => NULL, 'name' => 'Tables', 'slug' => 'tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 11, 'parent_id' => 10, 'name' => 'Plastic Tables', 'slug' => 'plastic-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 12, 'parent_id' => 11, 'name' => 'Plastic Rectangle Tables', 'slug' => 'plastic-rectangle-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 13, 'parent_id' => 11, 'name' => 'Plastic Round Tables', 'slug' => 'plastic-round-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 14, 'parent_id' => 10, 'name' => 'Wood Tables', 'slug' => 'wood-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 15, 'parent_id' => 14, 'name' => 'Wood Rectangle Tables', 'slug' => 'wood-rectangle-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 16, 'parent_id' => 14, 'name' => 'Wood Round Tables', 'slug' => 'wood-round-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 17, 'parent_id' => 14, 'name' => 'Farm Tables', 'slug' => 'farm-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 18, 'parent_id' => 14, 'name' => 'Cocktail Tables', 'slug' => 'cocktail-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-19 03:09:17', 'thumbnail' => 'images/products/cocktail-table-36-round-w30-and-42-poles/26954fa994ab.jpg'],
            ['id' => 19, 'parent_id' => 10, 'name' => 'Tablecloths & Covers', 'slug' => 'tablecloths-and-covers', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 20, 'parent_id' => 10, 'name' => 'Table Parts & Dollies', 'slug' => 'table-parts-and-dollies', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 21, 'parent_id' => NULL, 'name' => 'Kids Chairs & Tables', 'slug' => 'kids-chairs-and-tables', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 22, 'parent_id' => NULL, 'name' => 'Chairs Covers & Cushions & Tablecloths', 'slug' => 'chairs-covers-and-cushions-and-tablecloths', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 23, 'parent_id' => NULL, 'name' => 'Dollies & Parts', 'slug' => 'dollies-and-parts', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 04:34:54', 'updated_at' => '2026-06-16 04:34:54', 'thumbnail' => NULL],
            ['id' => 24, 'parent_id' => 1, 'name' => 'Folding Chairs', 'slug' => 'folding-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 25, 'parent_id' => 1, 'name' => 'Stacking Chairs', 'slug' => 'stacking-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-19 03:11:08', 'thumbnail' => 'images/products/wood-chiavari-chair-with-free-cushion-champagne/fc6582eb4a9a.jpg'],
            ['id' => 26, 'parent_id' => 25, 'name' => 'Resin Chiavari Chairs', 'slug' => 'resin-chiavari-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 27, 'parent_id' => 25, 'name' => 'Resin Cross Back Chairs', 'slug' => 'resin-cross-back-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/farmhouse-resin-cross-back-chair-medium-with-black-grain-closeout/da209fe41a23.jpg'],
            ['id' => 28, 'parent_id' => 25, 'name' => 'Wood Chiavari Chairs', 'slug' => 'wood-chiavari-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 29, 'parent_id' => 25, 'name' => 'Wood Cross Back Chairs', 'slug' => 'wood-cross-back-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/farmhouse-cross-back-bar-stool-limewash/4d47311d218a.jpg'],
            ['id' => 30, 'parent_id' => 25, 'name' => 'Throne Chairs', 'slug' => 'throne-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/king-wingback-throne-chair-white-vinylgold-frame/5caf1d090530.jpg'],
            ['id' => 31, 'parent_id' => 25, 'name' => 'Banquet Chairs', 'slug' => 'banquet-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/crown-back-banquet-chair-gold-frame-with-beige-patterned-vinyl/2046245f3129.jpg'],
            ['id' => 32, 'parent_id' => 25, 'name' => 'Metal Chairs', 'slug' => 'metal-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 33, 'parent_id' => 25, 'name' => 'Stacking Chairs Cushions & Covers', 'slug' => 'stacking-chairs-cushions-and-covers', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 34, 'parent_id' => 25, 'name' => 'Stacking Chairs Parts & Dollies', 'slug' => 'stacking-chairs-parts-and-dollies', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-16 05:14:53', 'updated_at' => '2026-06-16 05:14:53', 'thumbnail' => NULL],
            ['id' => 37, 'parent_id' => NULL, 'name' => 'Bamboo Chairs', 'slug' => 'bamboo-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-18 08:08:35', 'updated_at' => '2026-06-18 08:08:35', 'thumbnail' => NULL],
            ['id' => 38, 'parent_id' => NULL, 'name' => 'Cross Back Chairs', 'slug' => 'cross-back-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-18 08:12:48', 'updated_at' => '2026-06-18 23:10:03', 'thumbnail' => 'images/products/farmhouse-timbertouch-resin-cross-back-chair-black/3698e5f401e5.jpeg'],
            ['id' => 40, 'parent_id' => NULL, 'name' => 'Metal Stacking Chairs', 'slug' => 'metal-stacking-chairs', 'description' => NULL, 'is_active' => 1, 'created_at' => '2026-06-18 10:16:02', 'updated_at' => '2026-06-19 03:11:08', 'thumbnail' => 'images/products/industrial-metal-chair-silver/e707f17ef3da.jpg'],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}