/* -------------------------------------------------------------------------- */
/*  Country / State / City data for dependent address dropdowns                */
/*                                                                             */
/*  Curated subset (US + CA). To add more locales, extend COUNTRIES,           */
/*  STATES_BY_COUNTRY, and CITIES_BY_STATE in lockstep — the city key is       */
/*  `${countryCode}-${stateCode}`.                                             */
/* -------------------------------------------------------------------------- */

export const COUNTRIES = [
    { code: 'US', name: 'United States' },
    { code: 'CA', name: 'Canada' },
];

export const STATES_BY_COUNTRY = {
    US: [
        { code: 'AL', name: 'Alabama' },
        { code: 'AK', name: 'Alaska' },
        { code: 'AZ', name: 'Arizona' },
        { code: 'AR', name: 'Arkansas' },
        { code: 'CA', name: 'California' },
        { code: 'CO', name: 'Colorado' },
        { code: 'CT', name: 'Connecticut' },
        { code: 'DE', name: 'Delaware' },
        { code: 'DC', name: 'District of Columbia' },
        { code: 'FL', name: 'Florida' },
        { code: 'GA', name: 'Georgia' },
        { code: 'HI', name: 'Hawaii' },
        { code: 'ID', name: 'Idaho' },
        { code: 'IL', name: 'Illinois' },
        { code: 'IN', name: 'Indiana' },
        { code: 'IA', name: 'Iowa' },
        { code: 'KS', name: 'Kansas' },
        { code: 'KY', name: 'Kentucky' },
        { code: 'LA', name: 'Louisiana' },
        { code: 'ME', name: 'Maine' },
        { code: 'MD', name: 'Maryland' },
        { code: 'MA', name: 'Massachusetts' },
        { code: 'MI', name: 'Michigan' },
        { code: 'MN', name: 'Minnesota' },
        { code: 'MS', name: 'Mississippi' },
        { code: 'MO', name: 'Missouri' },
        { code: 'MT', name: 'Montana' },
        { code: 'NE', name: 'Nebraska' },
        { code: 'NV', name: 'Nevada' },
        { code: 'NH', name: 'New Hampshire' },
        { code: 'NJ', name: 'New Jersey' },
        { code: 'NM', name: 'New Mexico' },
        { code: 'NY', name: 'New York' },
        { code: 'NC', name: 'North Carolina' },
        { code: 'ND', name: 'North Dakota' },
        { code: 'OH', name: 'Ohio' },
        { code: 'OK', name: 'Oklahoma' },
        { code: 'OR', name: 'Oregon' },
        { code: 'PA', name: 'Pennsylvania' },
        { code: 'RI', name: 'Rhode Island' },
        { code: 'SC', name: 'South Carolina' },
        { code: 'SD', name: 'South Dakota' },
        { code: 'TN', name: 'Tennessee' },
        { code: 'TX', name: 'Texas' },
        { code: 'UT', name: 'Utah' },
        { code: 'VT', name: 'Vermont' },
        { code: 'VA', name: 'Virginia' },
        { code: 'WA', name: 'Washington' },
        { code: 'WV', name: 'West Virginia' },
        { code: 'WI', name: 'Wisconsin' },
        { code: 'WY', name: 'Wyoming' },
    ],
    CA: [
        { code: 'AB', name: 'Alberta' },
        { code: 'BC', name: 'British Columbia' },
        { code: 'MB', name: 'Manitoba' },
        { code: 'NB', name: 'New Brunswick' },
        { code: 'NL', name: 'Newfoundland and Labrador' },
        { code: 'NS', name: 'Nova Scotia' },
        { code: 'NT', name: 'Northwest Territories' },
        { code: 'NU', name: 'Nunavut' },
        { code: 'ON', name: 'Ontario' },
        { code: 'PE', name: 'Prince Edward Island' },
        { code: 'QC', name: 'Quebec' },
        { code: 'SK', name: 'Saskatchewan' },
        { code: 'YT', name: 'Yukon' },
    ],
};

export const CITIES_BY_STATE = {
    // United States
    'US-AL': ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
    'US-AK': ['Anchorage', 'Fairbanks', 'Juneau'],
    'US-AZ': ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
    'US-AR': ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale'],
    'US-CA': ['Los Angeles', 'San Diego', 'San Francisco', 'San Jose', 'Sacramento', 'Fresno', 'Long Beach', 'Oakland', 'Covina'],
    'US-CO': ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'],
    'US-CT': ['Hartford', 'New Haven', 'Stamford', 'Bridgeport', 'Waterbury'],
    'US-DE': ['Wilmington', 'Dover', 'Newark'],
    'US-DC': ['Washington'],
    'US-FL': ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 'Fort Lauderdale'],
    'US-GA': ['Atlanta', 'Augusta', 'Savannah', 'Athens', 'Macon', 'Columbus'],
    'US-HI': ['Honolulu', 'Hilo', 'Kailua'],
    'US-ID': ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'],
    'US-IL': ['Chicago', 'Aurora', 'Rockford', 'Springfield', 'Peoria', 'Naperville'],
    'US-IN': ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Bloomington'],
    'US-IA': ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
    'US-KS': ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'],
    'US-KY': ['Louisville', 'Lexington', 'Bowling Green', 'Frankfort'],
    'US-LA': ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
    'US-ME': ['Portland', 'Lewiston', 'Bangor', 'Augusta'],
    'US-MD': ['Baltimore', 'Columbia', 'Annapolis', 'Frederick', 'Rockville'],
    'US-MA': ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
    'US-MI': ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Warren'],
    'US-MN': ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'],
    'US-MS': ['Jackson', 'Gulfport', 'Biloxi', 'Hattiesburg'],
    'US-MO': ['Kansas City', 'Saint Louis', 'Springfield', 'Columbia', 'Jefferson City'],
    'US-MT': ['Billings', 'Missoula', 'Great Falls', 'Helena', 'Bozeman'],
    'US-NE': ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
    'US-NV': ['Las Vegas', 'Henderson', 'Reno', 'Carson City', 'Sparks'],
    'US-NH': ['Manchester', 'Nashua', 'Concord', 'Dover'],
    'US-NJ': ['Newark', 'Jersey City', 'Paterson', 'Trenton', 'Edison'],
    'US-NM': ['Albuquerque', 'Las Cruces', 'Santa Fe', 'Rio Rancho'],
    'US-NY': ['New York', 'Buffalo', 'Rochester', 'Albany', 'Syracuse', 'Yonkers'],
    'US-NC': ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
    'US-ND': ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'],
    'US-OH': ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'],
    'US-OK': ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
    'US-OR': ['Portland', 'Salem', 'Eugene', 'Bend', 'Gresham'],
    'US-PA': ['Philadelphia', 'Pittsburgh', 'Harrisburg', 'Allentown', 'Erie'],
    'US-RI': ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
    'US-SC': ['Charleston', 'Columbia', 'Greenville', 'Mount Pleasant'],
    'US-SD': ['Sioux Falls', 'Rapid City', 'Pierre', 'Aberdeen'],
    'US-TN': ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
    'US-TX': ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso', 'Arlington'],
    'US-UT': ['Salt Lake City', 'West Valley City', 'Provo', 'Ogden', 'Sandy'],
    'US-VT': ['Burlington', 'Montpelier', 'Rutland', 'South Burlington'],
    'US-VA': ['Virginia Beach', 'Norfolk', 'Richmond', 'Arlington', 'Chesapeake'],
    'US-WA': ['Seattle', 'Spokane', 'Tacoma', 'Olympia', 'Bellevue'],
    'US-WV': ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
    'US-WI': ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
    'US-WY': ['Cheyenne', 'Casper', 'Laramie', 'Gillette'],
    // Canada
    'CA-AB': ['Calgary', 'Edmonton', 'Red Deer', 'Lethbridge'],
    'CA-BC': ['Vancouver', 'Victoria', 'Surrey', 'Burnaby', 'Richmond'],
    'CA-MB': ['Winnipeg', 'Brandon', 'Steinbach'],
    'CA-NB': ['Moncton', 'Saint John', 'Fredericton'],
    'CA-NL': ["St. John's", 'Mount Pearl', 'Corner Brook'],
    'CA-NS': ['Halifax', 'Sydney', 'Dartmouth'],
    'CA-NT': ['Yellowknife', 'Hay River'],
    'CA-NU': ['Iqaluit'],
    'CA-ON': ['Toronto', 'Ottawa', 'Mississauga', 'Hamilton', 'Brampton', 'London'],
    'CA-PE': ['Charlottetown', 'Summerside'],
    'CA-QC': ['Montreal', 'Quebec City', 'Laval', 'Gatineau', 'Sherbrooke'],
    'CA-SK': ['Saskatoon', 'Regina', 'Prince Albert'],
    'CA-YT': ['Whitehorse'],
};

export function getStates(countryCode) {
    return STATES_BY_COUNTRY[countryCode] || [];
}

export function getCities(countryCode, stateCode) {
    if (!countryCode || !stateCode) return [];
    return CITIES_BY_STATE[`${countryCode}-${stateCode}`] || [];
}
